const fs = require('fs');
const path = require('path');

const rawUnions = [
  {
    number: 1,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Americana e Região",
    cnpj: "52.154.184/0001-48",
    address: "Rua Tamoio, 88 - Jardim Santa Catarina",
    city: "Americana",
    state: "SP",
    cep: "13.466-250",
    phone: "(19) 3462.1926 e 3462.1364",
    email: "secretaria.sindiamericana@gmail.com",
    website: "https://www.sindicatoamericana.com.br",
    president: "Claudemir Alves da Cruz",
    region: "Região Metropolitana de Campinas / Piracicaba",
    category: "Transporte Rodoviário e Passageiros"
  },
  {
    number: 2,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Trabalhadores em Transportes de Cargas em Geral e Urbanos de Passageiros de Araçatuba",
    cnpj: "55.752.851/0001-82",
    address: "Rua Cândido Portinari 966 - Jd Nova Yorque",
    city: "Araçatuba",
    state: "SP",
    cep: "16.018-220",
    phone: "(18) 3623.5291 e (14) 99646.6830",
    email: "fttrespsincover@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Dorival dos Santos Junior",
    region: "Interior (Noroeste Paulista)",
    category: "Cargas em Geral e Urbano de Passageiros"
  },
  {
    number: 3,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários, Urbanos e das Indústrias de Cana de Açúcar de Araraquara e Região",
    cnpj: "57.712.234/0001-89",
    address: "Rua Dr. Freire Júnior, nº 43 - Vila Furlan",
    city: "Araraquara",
    state: "SP",
    cep: "14.807-009",
    phone: "(16) 3322-4311",
    email: "sindtranspararaq@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Rogério Adriano Bandeira",
    region: "Central Paulista",
    category: "Rodoviários, Urbanos e Setor Sucroalcooleiro"
  },
  {
    number: 4,
    name: "Sindicato dos Trabalhadores no Setor de Transportes Rodoviários das Usinas e Agropecuárias Ligadas de Araras, Leme e Conchal",
    cnpj: "00.456.823/0001-26",
    address: "Rua Arceu Scanavini, 26 - Jd. Florença",
    city: "Araras",
    state: "SP",
    cep: "13600-000",
    phone: "(19) 3541.9776",
    email: "sttrualc@terra.com.br",
    website: "https://www.fttresp.org.br",
    president: "Odair Pires",
    region: "Central / Campinas",
    category: "Usina, Agropecuária e Rodoviários"
  },
  {
    number: 5,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Anexos de Assis",
    cnpj: "54.720.065/0001-30",
    address: "Rua Capitão Assis, 315 – Centro",
    city: "Assis",
    state: "SP",
    cep: "19.800-061",
    phone: "(18) 3322.5582",
    email: "sindicato.scvra@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Renato Manoel Raposo",
    region: "Alta Sorocabana / Oeste",
    category: "Condutores Rodoviários e Anexos"
  },
  {
    number: 6,
    name: "Sindicato dos Motoristas de Veículos Rodoviários e Trabalhadores em Transportes Urbanos e Intermunicipais de Passageiros e Cargas Secas e Molhadas de Atibaia e Região",
    cnpj: "04.160.294/0001-70",
    address: "Rua José Bim, 567 Centro",
    city: "Atibaia",
    state: "SP",
    cep: "12940-640",
    phone: "(11) 4418.2600",
    email: "presidencia@sindmaratibaia.com.br",
    website: "https://www.sindmaratibaia.com.br",
    president: "Jorge Camargo Baptista",
    region: "Região Bragantina",
    category: "Urbano, Intermunicipal e Cargas"
  },
  {
    number: 7,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Barra Bonita",
    cnpj: "54.713.441/0001-60",
    address: "Rua Antônio Argemiro Ferreira, nº 60 – Jardim Nova Barra",
    city: "Barra Bonita",
    state: "SP",
    cep: "17.340-000",
    phone: "(14) 3641.0316",
    email: "sindtransbarrabonita@sindtransbarrabonita.com.br",
    website: "https://www.sindtransbarrabonita.com.br",
    president: "Antônio Aparecido de Camargo",
    region: "Central / Bauru",
    category: "Transportes Rodoviários"
  },
  {
    number: 8,
    name: "Sindicato dos Condutores de Veículos e Trabalhadores em Transportes Rodoviários de Barretos",
    cnpj: "57.719.064/0001-64",
    address: "Rua Santa Ernestina, 193 - Sumaré",
    city: "Barretos",
    state: "SP",
    cep: "14781-042",
    phone: "(17) 3322.5439",
    email: "sindtransporte@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Sidnei Vilela dos Santos",
    region: "Norte Paulista",
    category: "Condutores e Rodoviários"
  },
  {
    number: 9,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Trabalhadores nas Empresas de Transporte Urbano, Passageiros e Fretamento, Intermunicipal e Interestadual e Cargas Secas e Molhadas, Motoristas, Tratoristas e Operadores de Máquinas de Usinas de Açúcar e Álcool e Destilarias de Batatais",
    cnpj: "08.008.000/0001-40",
    address: "Rua Dr. José Garcia de Barros, 82, Santo Antônio",
    city: "Batatais",
    state: "SP",
    cep: "14315-132",
    phone: "(16) 99794.6895",
    email: "sindimob.sp@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Paulo Alexandre Martins de Bastos",
    region: "Ribeirão Preto / Franca",
    category: "Urbano, Fretamento, Cargas e Usinas"
  },
  {
    number: 10,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Bauru – SINDTRAN",
    cnpj: "51.510.642/0001-71",
    address: "Rua Boa Esperança, nº 2-54, Vila Seabra",
    city: "Bauru",
    state: "SP",
    cep: "17060-010",
    phone: "(14) 3233.6420",
    email: "sindtran@terra.com.br",
    website: "https://www.sindtran.com.br",
    president: "Reinaldo Donizete da Silva",
    region: "Centro-Oeste Paulista",
    category: "Transportes Rodoviários e Urbano"
  },
  {
    number: 11,
    name: "Sindicato dos Empregados em Escritórios e no Setor Administrativo de Empresas de Transportes Rodoviários de Cargas em Geral, Passageiros, Urbano, Fretamento e Logística em Transportes de Campinas, Piracicaba, Ribeirão Preto e Regiões – SINDCAPRI",
    cnpj: "00.183.352/0001-20",
    address: "Rua Baronesa Geraldo de Resende, 863",
    city: "Campinas",
    state: "SP",
    cep: "13075-270",
    phone: "(19) 3242.9027 e 3243.6749",
    email: "sindcapri@uol.com.br",
    website: "https://www.sindcapri.com.br",
    president: "Luiz Roberto Castelhano",
    region: "Campinas, Piracicaba e Ribeirão Preto",
    category: "Administrativo e Escritórios de Transportes"
  },
  {
    number: 12,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Campinas e Região",
    cnpj: "51.909.356/0001-83",
    address: "Rua Bernardino de Campos, 115 Centro",
    city: "Campinas",
    state: "SP",
    cep: "13010-150",
    phone: "(19) 3731.8200",
    email: "sttrcr@terra.com.br",
    website: "https://www.rodoviarioscampinas.org.br",
    president: "Alessandro Aparecido Leite Martins",
    region: "Região Metropolitana de Campinas",
    category: "Transportes Rodoviários e Urbano"
  },
  {
    number: 13,
    name: "Sindicato dos Trabalhadores em Empresas de Transportes Rodoviários de Cargas, Secas, Molhadas, Líquidas e Gasosas, Vivas, Próprias e Trabalhadores Motoristas e Ajudantes nas Empresas de Materiais de Construção, Depósito de Bebidas, Supermercados, Trabalhadores nas Empresas Coletoras de Lixo e Concreteiras de Campinas e região - Sindicargas Campinas",
    cnpj: "01.584.678/0001-21",
    address: "Rua Amador Florence, 141 – Botafogo",
    city: "Campinas",
    state: "SP",
    cep: "13020-290",
    phone: "(19) 3231.4015 e 2121-3010",
    email: "secretaria@sindcargascampinas.com.br",
    website: "https://www.sindcargascampinas.com.br",
    president: "Paulo Vicente Ferreira",
    region: "Região Metropolitana de Campinas",
    category: "Cargas, Lixo, Bebidas e Concreteiras"
  },
  {
    number: 14,
    name: "Sindicato dos condutores de veículos Rodoviários e Anexos da Região Osvaldo Cruz, Adamantina e Dracena",
    cnpj: "57.326.654/0001-27",
    address: "Rua Edson da Silveira Campos, 1.274",
    city: "Dracena",
    state: "SP",
    cep: "17.900-000",
    phone: "(18) 3822.6540 e 3821.5925",
    email: "secretaria@sindicatocondutoresdracena.com.br",
    website: "https://www.sindicatocondutoresdracena.com.br",
    president: "Luis Sapucaia",
    region: "Nova Alta Paulista",
    category: "Condutores Rodoviários e Anexos"
  },
  {
    number: 15,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Trabalhadores em Empresas de Transportes de Cargas Secas e Molhadas em Geral, Cargas Líquidas, Cargas Pesadas, Super Pesadas, Ajudantes e Arrumadores, de Ferraz de Vasconcelos, Poá e Itaquaquecetuba",
    cnpj: "08.883.028/0001-26",
    address: "Rua Caxambu, 142 - Vila Zeferina",
    city: "Itaquaquecetuba",
    state: "SP",
    cep: "08576-010",
    phone: "(11) 4676.4429",
    email: "sindicarga@terra.com.br",
    website: "https://www.fttresp.org.br",
    president: "Samuel de Souza",
    region: "Alto Tietê / Grande SP",
    category: "Cargas Secas, Molhadas e Pesadas"
  },
  {
    number: 16,
    name: "Sindicato dos Condutores de Veículos Rodoviários de Franca e Região",
    cnpj: "47.985.213/0001-83",
    address: "Rua Cavalheiro Petraglia, 459 - Vila Santos Dumont",
    city: "Franca",
    state: "SP",
    cep: "14405-327",
    phone: "(16) 3723.9510",
    email: "guias@sindicatomotoristas.com.br",
    website: "https://www.sindicatomotoristas.com.br",
    president: "Geraldo Xavier de Almeida",
    region: "Nordeste Paulista",
    category: "Condutores Rodoviários e Urbano"
  },
  {
    number: 17,
    name: "Sindicato dos Condutores e Trabalhadores nas Empresas de Transporte de Guaíra e Região",
    cnpj: "03.900.823/0001-61",
    address: "Rua Trinta e oito, 111 – Campos Elíseos",
    city: "Guaíra",
    state: "SP",
    cep: "14790-000",
    phone: "(17) 3331.8120",
    email: "contato@sindgua.org.br",
    website: "https://www.sindgua.org.br",
    president: "George Ribeiro Guimarães",
    region: "Norte Paulista / Barretos",
    category: "Condutores e Transportes"
  },
  {
    number: 18,
    name: "Sindicato dos Motoristas, Tratoristas e Operadores de Máquinas Agrícolas de Usinas de Açúcar, Destilarias de Álcool, Fazendas e Sítios de Guariba",
    cnpj: "04.400.185/0001-82",
    address: "Avenida da Saudade, 345 - Vila Garavelo",
    city: "Guariba",
    state: "SP",
    cep: "14840-000",
    phone: "(16) 3251-5353",
    email: "sindmotrop@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Antônio de Jesus Viana",
    region: "Jaboticabal / Araraquara",
    category: "Usinas, Destilarias e Máquinas Agrícolas"
  },
  {
    number: 19,
    name: "Sindicato dos Empregados em Empresas de Transportes Rodoviários, Cargas Secas e Molhadas e Anexos de Guarulhos e Região",
    cnpj: "04.276.287/0001-38",
    address: "Avenida José Lourenço Neves, 346 - Jd. Bom Clima",
    city: "Guarulhos",
    state: "SP",
    cep: "07122-070",
    phone: "(11) 2441.4974",
    email: "sindicargas_guarulhos@yahoo.com.br",
    website: "https://www.fttresp.org.br",
    president: "Irapuan Siqueira Souza",
    region: "Grande São Paulo",
    category: "Cargas Secas e Molhadas"
  },
  {
    number: 20,
    name: "Sindicato dos Empregados em Escritórios de Empresas de Transportes Rodoviário Urbano de Passageiro, Rodoviário Intermunicipal, Rodoviário Interestadual, Rodoviário de Turismo e Fretamento de Guarulhos e Região - SINDIESCRIT",
    cnpj: "74.504.481/0001-09",
    address: "Rua Ipê, 168 - Jd. Guarulhos",
    city: "Guarulhos",
    state: "SP",
    cep: "07090-130",
    phone: "(11) 2475.2923 e 2440.6998",
    email: "sindiescritsede@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "José Rogério Vieira",
    region: "Grande São Paulo",
    category: "Escritórios de Transportes Rodoviários"
  },
  {
    number: 21,
    name: "Sindicato dos Trabalhadores Rodoviários no Transportes de Passageiros, Urbanos, Suburbano, Metropolitano, Intermunicipal e Cargas Próprias de Guarulhos e Arujá – SINCOVERG",
    cnpj: "58.479.999/0001-83",
    address: "Rua Jaiminho, 215 - Vila Progresso",
    city: "Guarulhos",
    state: "SP",
    cep: "07095-150",
    phone: "(11) 2382.2923 e 2441.3442",
    email: "cadastro@sincoverg.org.br",
    website: "https://www.sincoverg.org.br",
    president: "Orlando Maurício Junior",
    region: "Guarulhos e Arujá",
    category: "Passageiros, Urbano e Cargas Próprias"
  },
  {
    number: 22,
    name: "Sindicato dos Trabalhadores em Empresas de Transporte Rodoviários Interestaduais de Passageiros de Guarulhos e Região - Sinterg",
    cnpj: "04.925.071/0001-56",
    address: "Rua Túlio Brancaleoni, 119 – Jd. São Paulo",
    city: "Guarulhos",
    state: "SP",
    cep: "07110-030",
    phone: "(11) 2488.6077",
    email: "adm@sinterg.org",
    website: "https://www.sinterg.org",
    president: "Sizernando Elias Correia de Farias",
    region: "Grande São Paulo",
    category: "Interestadual de Passageiros"
  },
  {
    number: 23,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Itápolis",
    cnpj: "02.344.168/0001-40",
    address: "Avenida dos Amaros, 873",
    city: "Itápolis",
    state: "SP",
    cep: "14900-000",
    phone: "(16) 3263.1042",
    email: "sindicatotransporteitapolis@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Daniel de Oliveira",
    region: "Central Paulista",
    category: "Transportes Rodoviários"
  },
  {
    number: 24,
    name: "Sindicato dos Condutores de Veículos Rodoviários de Itu e Região",
    cnpj: "48.989.396/0001-78",
    address: "Rua Arthuro Ianni, 622 – Vila Ianni",
    city: "Itu",
    state: "SP",
    cep: "13313-150",
    phone: "(11) 4023.3185",
    email: "contato@sindcondutoresitu.com.br",
    website: "https://www.sindcondutoresitu.com.br",
    president: "Vitor Ribeiro de Carvalho",
    region: "Região Metropolitana de Sorocaba",
    category: "Condutores Rodoviários"
  },
  {
    number: 25,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Jaboticabal",
    cnpj: "57.713.471/0001-64",
    address: "Rua Juca Quito, 711 - Centro",
    city: "Jaboticabal",
    state: "SP",
    cep: "14870-260",
    phone: "(16) 3209.3141",
    email: "sttrj.jal@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Valdenir Oscar Bonatti",
    region: "Ribeirão Preto / Araraquara",
    category: "Transportes Rodoviários"
  },
  {
    number: 26,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Jales e Região",
    cnpj: "00.446.833/0001-80",
    address: "Rua Idair Lopes, 895 - Aeroporto",
    city: "Jales",
    state: "SP",
    cep: "15704-472",
    phone: "(17) 3624.4848",
    email: "presidencia@sindmotoristasjales.com.br",
    website: "https://www.sindmotoristasjales.com.br",
    president: "José Roberto Duarte da Silveira",
    region: "Noroeste Paulista",
    category: "Transportes Rodoviários"
  },
  {
    number: 27,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Jau e Região",
    cnpj: "51.496.669/0001-57",
    address: "Rua Treze de Maio, 526",
    city: "Jaú",
    state: "SP",
    cep: "17201-420",
    phone: "(14) 3622.4080",
    email: "sindicato@sindtransportesjau.com.br",
    website: "https://www.sindtransportesjau.com.br",
    president: "Mário Eziquiel Perobelli",
    region: "Central Paulista",
    category: "Transportes Rodoviários"
  },
  {
    number: 28,
    name: "Sindicato dos Trabalhadores nas Empresas de Transportes Rodoviários de Cargas Secas e Molhadas e Setor Diferenciado de Jundiaí e Região - SINTRACARGAS",
    cnpj: "13.357.846/0001-25",
    address: "Avenida Jundiaí 268/272 - Anhangabaú",
    city: "Jundiaí",
    state: "SP",
    cep: "13214-206",
    phone: "(11) 4521.4476 e 4521.8104",
    email: "presidencia@sintracargas.org.br",
    website: "https://www.sintracargas.org.br",
    president: "Reinaldo Dias Rabelo",
    region: "Aglomeração Urbana de Jundiaí",
    category: "Cargas Secas, Molhadas e Setor Diferenciado"
  },
  {
    number: 29,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Jundiaí e Região",
    cnpj: "44.657.856/0001-00",
    address: "Rua Baronesa de Japi, 398",
    city: "Jundiaí",
    state: "SP",
    cep: "13207-684",
    phone: "(11) 4521.8267 e 93754.0594",
    email: "financeiro1@sttrjr.org.br",
    website: "https://www.rodoviariosjundiai.org.br",
    president: "Emerson de Moraes Lopes",
    region: "Aglomeração Urbana de Jundiaí",
    category: "Transportes Rodoviários"
  },
  {
    number: 30,
    name: "Sindicato dos Condutores de Veículos e Trabalhadores de Transportes Rodoviários, Urbanos e de Passageiros de Lençóis Paulista - SINCOVELPA",
    cnpj: "51.519.585/0001-91",
    address: "Rua Pedro Natalio Lorenzetti, 180 - Centro",
    city: "Lençóis Paulista",
    state: "SP",
    cep: "18680-110",
    phone: "(14) 3263-1098",
    email: "dpessoal@sincovelpa.com.br",
    website: "https://www.sincovelpa.com.br",
    president: "José Pintor",
    region: "Bauru / Jaú",
    category: "Rodoviários, Urbanos e Passageiros"
  },
  {
    number: 31,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Trabalhadores em Transportes Urbanos de Passageiros de Limeira",
    cnpj: "56.980.816/0001-83",
    address: "Rua Joaquim Rodrigues de Oliveira, 381 - Vila Santa Lina",
    city: "Limeira",
    state: "SP",
    cep: "13480-480",
    phone: "(19) 3441.0548",
    email: "tesouraria@sindmotorista.com.br",
    website: "https://www.sindmotorista.com.br",
    president: "Benedito Honorio Barbosa",
    region: "Piracicaba / Campinas",
    category: "Transportes Urbanos de Passageiros"
  },
  {
    number: 32,
    name: "Sindicato dos Trabalhadores do Transporte Urbano de Limeira – Sinditrul",
    cnpj: "08.946.243/0001-29",
    address: "Rua Dr. Sebastiao Toledo Barros, 44, Centro",
    city: "Limeira",
    state: "SP",
    cep: "13480-222",
    phone: "(19) 3451.9063",
    email: "sindttrul@yahoo.com.br",
    website: "https://www.fttresp.org.br",
    president: "Alex Aparecido de Oliveira",
    region: "Piracicaba / Campinas",
    category: "Transporte Urbano de Limeira"
  },
  {
    number: 33,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Anexos de Lins",
    cnpj: "54.722.129/0001-32",
    address: "Rua Jonas Carlos Arantes, 242 – Jardim Americano",
    city: "Lins",
    state: "SP",
    cep: "16400-509",
    phone: "(14) 3523.7722",
    email: "sicovel@terra.com.br",
    website: "https://www.fttresp.org.br",
    president: "José Carlos Pereira dos Santos",
    region: "Centro-Oeste Paulista",
    category: "Condutores Rodoviários e Anexos"
  },
  {
    number: 34,
    name: "Sindicato dos Motoristas, Trabalhadores nas Empresas de Transportes de Passageiros Urbanos, Metropolitano, Rodoviários, Transportes de Cargas Secas, Líquidas em Geral, Limpeza Urbana Pública e Privada e das Categorias Diferenciadas do Litoral Norte de São Paulo",
    cnpj: "67.658.443/0001-45",
    address: "Av. Goiás, 574 - Jardim Indaiá",
    city: "Caraguatatuba",
    state: "SP",
    cep: "11665-120",
    phone: "(12) 3600.9920 e 97404.6773",
    email: "sttruca@uol.com.br",
    website: "https://www.sttruca.com.br",
    president: "Francisco Israel",
    region: "Litoral Norte (Caraguatatuba, Ubatuba, São Sebastião, Ilhabela)",
    category: "Urbano, Rodoviário, Cargas e Limpeza Urbana"
  },
  {
    number: 35,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários e Urbanos de Marilia e Região",
    cnpj: "51.512.754/0001-61",
    address: "Rua Marcos Bortion, 815 - Santa Antonieta",
    city: "Marília",
    state: "SP",
    cep: "17512-330",
    phone: "(14) 3425.1331",
    email: "rodov@terra.com.br",
    website: "https://www.sindicatodosmotoristas.com.br",
    president: "Josué Domingues de Mattos",
    region: "Centro-Oeste / Marília",
    category: "Rodoviários e Urbanos"
  },
  {
    number: 36,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Anexos de Matão",
    cnpj: "57.718.520/0001-51",
    address: "Rua Affonso Maccagnan, 319 - Centro",
    city: "Matão",
    state: "SP",
    cep: "15990-680",
    phone: "(16) 3382.5966",
    email: "sindicatodoscondutoresdematao@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Daniel Flois Macedo",
    region: "Araraquara / São Carlos",
    category: "Condutores Rodoviários e Anexos"
  },
  {
    number: 37,
    name: "Sindicato dos Condutores de Veículos Rodoviários de Mococa e Região",
    cnpj: "54.140.660/0001-05",
    address: "Rua Canadá, 185 - Jd. Lavínia",
    city: "Mococa",
    state: "SP",
    cep: "13736-340",
    phone: "(19) 3656.9100",
    email: "condutoresmococa@hotmail.com",
    website: "https://www.sindmotmococa.com.br",
    president: "Nelson Ribeiro da Silva",
    region: "Mogi Mirim / São João da Boa Vista",
    category: "Condutores Rodoviários"
  },
  {
    number: 38,
    name: "Sindicato dos Trabalhadores em Empresas de Transportes Rodoviários e Anexos, Ônibus Urbano, Turismo e Fretamento, Cargas Líquidas, Super Pesadas, Entregadores de Gás, Entregadores de Mercadorias, Diferenciados e Cargas Secas e Molhadas em Geral de Mogi das Cruzes",
    cnpj: "58.485.616/0001-80",
    address: "Av. Governador Ademar de Barros, 413 - Vila Rubens",
    city: "Mogi das Cruzes",
    state: "SP",
    cep: "08735-010",
    phone: "(11) 4724.9678",
    email: "secretaria_sindrodov@terra.com.br",
    website: "https://www.sindicatodosrodoviariosmogi.org",
    president: "Felix Serrano de Barros",
    region: "Alto Tietê / Grande SP",
    category: "Urbano, Fretamento, Entregadores e Cargas"
  },
  {
    number: 39,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Trabalhadores em Transportes, Urbano de Passageiros, Turismo, Cargas Secas e Molhadas, Depósitos e Fretamento do Comercio e Industria de Mogi Guaçu e Região",
    cnpj: "67.168.807/0001-09",
    address: "Rua Jaime de Oliveira, 71, Imóvel Pedregulhal",
    city: "Mogi Guaçu",
    state: "SP",
    cep: "13845-222",
    phone: "(19) 3891.6786",
    email: "atendimento@sindcondutoresmg.com.br",
    website: "https://www.sindcondutoresmg.com.br",
    president: "Gessy Alves de Oliveira",
    region: "Baixa Mogiana",
    category: "Passageiros, Turismo, Fretamento e Cargas"
  },
  {
    number: 40,
    name: "Sindicato dos Motoristas e Trabalhadores do Ramo de Transportes de Empresas de Cargas Secas e Molhadas e Diferenciados do Comercio, Industria, Gás, Estabelecimentos Bancários e Financeiros de Osasco e região - Simtratecor",
    cnpj: "03.172.523/0001-03",
    address: "Rua dos Marianos, 123 – Centro",
    city: "Osasco",
    state: "SP",
    cep: "06016-050",
    phone: "(11) 3651.7809",
    email: "secretaria@simtratecor.net.br",
    website: "https://www.simtratecor.com.br",
    president: "Reginaldo Nunes dos Santos",
    region: "Oeste da Grande SP",
    category: "Cargas Secas, Molhadas, Gás e Comércio"
  },
  {
    number: 41,
    name: "Sindicato Dos Empregados Administrativos em Empresas de Transporte Rodoviário e Logística de Cargas Secas Emolhadas, Rodoviários Urbanos de Passageiros, Intermunicipal, Interestadual, Suburbano e Fretamento de Osasco, Sorocaba, Vale do Ribeira e respectivas regiões-SP - SINETROSV",
    cnpj: "02.465.743/0001-62",
    address: "Rua Dr. Mariano Jatati Marcondes Ferraz, 509 – Centro",
    city: "Osasco",
    state: "SP",
    cep: "06097-010",
    phone: "(11) 3699-0575 e 2284-1675",
    email: "sinetrosv@sinetrosv.org.br",
    website: "https://www.sinetrosv.org.br",
    president: "Arnaldo Ribeiro da Silva",
    region: "Osasco, Sorocaba e Vale do Ribeira",
    category: "Administrativo e Logística de Transportes"
  },
  {
    number: 42,
    name: "Sindicato dos Motoristas de Veículos Rodoviários e Trabalhadores em Empresas de Transportes Rodoviários de Osasco e Região - SINCOVERO",
    cnpj: "56.334.758/0001-10",
    address: "Rua Presidente Castelo Branco, 56",
    city: "Osasco",
    state: "SP",
    cep: "06016-020",
    phone: "(11) 3685.4333 e 3681.1738",
    email: "sincovero@hotmail.com",
    website: "https://www.sincovero.com",
    president: "Itamar Donizetti Luiz",
    region: "Oeste da Grande SP",
    category: "Motoristas Rodoviários e Urbano"
  },
  {
    number: 43,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Ourinhos e Anexos",
    cnpj: "54.710.751/0001-20",
    address: "Rua Rinkuro Suzuki, 60 - Pq. Valeriano Marcante",
    city: "Ourinhos",
    state: "SP",
    cep: "19911-445",
    phone: "(14) 3322.7199",
    email: "sindicatorodoviarioourinhos@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Roque Fermino Marcelino",
    region: "Sorocabana / Ourinhos",
    category: "Transportes Rodoviários e Anexos"
  },
  {
    number: 44,
    name: "Sindicato dos Condutores de Veículos Rodoviários, Fretamento, Usinas e Transportes de Cargas Secas e Molhadas de Piracicaba - SIFRUCAP",
    cnpj: "51.419.778/0001-70",
    address: "Rua Bernardino de Campos, 1.426/1.430 - bairro Alto",
    city: "Piracicaba",
    state: "SP",
    cep: "13419-100",
    phone: "(19) 3375.4150 e 98195.5790",
    email: "sifrucap@hotmail.com",
    website: "https://www.sifrucap.com.br",
    president: "Alex de Assis Paes",
    region: "Metropolitana de Piracicaba",
    category: "Fretamento, Usinas e Cargas Secas"
  },
  {
    number: 45,
    name: "Sindicato dos Trabalhadores em Transportes Urbano de Piracicaba e Região - STTUP",
    cnpj: "06.093.120/0001-67",
    address: "Rua Floriano Peixoto, 1.046 - Centro",
    city: "Piracicaba",
    state: "SP",
    cep: "13400-520",
    phone: "(19) 3042.4707",
    email: "sinttransp@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "João José Soares",
    region: "Metropolitana de Piracicaba",
    category: "Transporte Urbano de Passageiros"
  },
  {
    number: 46,
    name: "Sindicato dos Motoristas em Empresas de Transportes Rodoviários, Urbanos de Passageiros, Fretamento, Usinas e Destilarias de Açúcar e Álcool, Condomínios, Sítios e Fazendas de Pitangueiras",
    cnpj: "08.846.975/0001-47",
    address: "Rua Pernambuco, 61- Centro",
    city: "Pitangueiras",
    state: "SP",
    cep: "14750-000",
    phone: "(16) 3952.0805",
    email: "sindmotpitangueiras@hotmail.com",
    website: "https://www.sindmotpitangueiras.com",
    president: "Devalde Paulo Curci",
    region: "Ribeirão Preto / Sertãozinho",
    category: "Rodoviários, Fretamento e Usinas"
  },
  {
    number: 47,
    name: "Sindicato dos Trabalhadores em Empresas de Transportes Rodoviários em Geral de Cargas Secas e Molhadas, Empresas de Logística do Ramo de Transportes de Cargas e Empresas de Transportes Urbano, Fretamento e Turismo de Porto Ferreira e Região – SindiRodoviários",
    cnpj: "56.988.751/0001-12",
    address: "Rua Luiz Gama, 424, Sala 02",
    city: "Porto Ferreira",
    state: "SP",
    cep: "13660-000",
    phone: "(19) 3581.2261",
    email: "sindicatocondutores@uol.com.br",
    website: "https://www.fttresp.org.br",
    president: "Júnior Aparecido Marinho",
    region: "São Carlos / Descalvado",
    category: "Cargas, Logística, Urbano e Fretamento"
  },
  {
    number: 48,
    name: "Sindicato dos Trabalhadores em Transportes Terrestres de Presidente Prudente e Região - SINTRATTEPP",
    cnpj: "11.432.305/0001-99",
    address: "Rua Casemiro Dias, 396",
    city: "Presidente Prudente",
    state: "SP",
    cep: "19010-280",
    phone: "(18) 3344.3108",
    email: "sindicato@sintrattepp.com.br",
    website: "https://www.sintrattepp.com.br",
    president: "Wagner Schiavão",
    region: "Oeste Paulista / Presidente Prudente",
    category: "Transportes Terrestres e Rodoviários"
  },
  {
    number: 49,
    name: "Sindicato dos Condutores de Veículos Rodoviários, Urbanos de Passageiros e Transportes de Cargas de Registro e Região",
    cnpj: "57.741.035/0001-07",
    address: "Rua Waldemar Lopes Ferraz, 233 - Vila Tupi",
    city: "Registro",
    state: "SP",
    cep: "11.900-000",
    phone: "(13) 3821.4955 e (13) 99719.7301",
    email: "sindicato.registro@terra.com.br",
    website: "https://www.fttresp.org.br",
    president: "Diretoria Colegiada",
    region: "Vale do Ribeira",
    category: "Condutores Rodoviários e Cargas"
  },
  {
    number: 50,
    name: "Sindicato dos Condutores de Veículos Rodoviários de Ribeirão Preto e Região - SINDCONDRP",
    cnpj: "56.013.428/0001-23",
    address: "Rua Sergipe, 173",
    city: "Ribeirão Preto",
    state: "SP",
    cep: "14080-040",
    phone: "(16) 3625.4326",
    email: "sind.cond@terra.com.br",
    website: "https://www.sindcondrp.com.br",
    president: "Walter Gomes de Oliveira",
    region: "Região Metropolitana de Ribeirão Preto",
    category: "Condutores Rodoviários"
  },
  {
    number: 51,
    name: "Sindicato dos Empregados em Empresas de Transporte Urbano e Suburbano de Passageiro de Ribeirão Preto e Região - SEETURP",
    cnpj: "66.995.622/0001-05",
    address: "Rua Dr. Loyola, 246/250",
    city: "Ribeirão Preto",
    state: "SP",
    cep: "14050-070",
    phone: "(16) 3235.0860",
    email: "seeturp@terra.com.br",
    website: "https://www.fttresp.org.br",
    president: "João Henrique Bueno",
    region: "Região Metropolitana de Ribeirão Preto",
    category: "Transporte Urbano e Suburbano"
  },
  {
    number: 52,
    name: "Sindicato dos Empregados no Setor Administrativo (Escritório) das Empresas de Transportes Rodoviários Urbano de Passageiros, Intermunicipal, Interestadual, Turismo e Fretamento de Ribeirão Preto, Araraquara e Regiões",
    cnpj: "06.022.346/0001-77",
    address: "Rua Florêncio de Abreu, 681- Vila Seixas",
    city: "Ribeirão Preto",
    state: "SP",
    cep: "14015-060",
    phone: "(16) 3941.1551",
    email: "sindicato.transporte@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Sérgio Aparecido Martins",
    region: "Ribeirão Preto e Araraquara",
    category: "Escritórios e Administrativo de Transportes"
  },
  {
    number: 53,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Rio Claro",
    cnpj: "46.958.609/0001-79",
    address: "Avenida 22, nº 233 - Vila Aparecida",
    city: "Rio Claro",
    state: "SP",
    cep: "13500-510",
    phone: "(19) 3524.9707 e (19) 9442.1117",
    email: "sttrrc.rioclaro@gmail.com",
    website: "https://www.sttrrc.org.br",
    president: "Waldemar Neuton da Silva",
    region: "Central Paulista / Rio Claro",
    category: "Transportes Rodoviários"
  },
  {
    number: 54,
    name: "Sindicato dos Condutores de Veículos Rodoviários, Urbanos, Passageiros e Anexos de Santo Anastácio",
    cnpj: "68.164.938/0001-80",
    address: "Av. Jorge Tibiriçá, 768 - Presidente Venceslau",
    city: "Santo Anastácio",
    state: "SP",
    cep: "19400-000",
    phone: "(18) 3272.2594",
    email: "sc-rodov-venceslau@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Elias Tolovi Rosa",
    region: "Presidente Prudente / Venceslau",
    category: "Condutores Rodoviários e Anexos"
  },
  {
    number: 55,
    name: "Sindicato dos Trabalhadores em Fiscalização, Inspeção e Controle Operacional nas Empresas de Transporte de Passageiros, Gestoras e Prestadoras de Serviços do ABC e Litoral Sul – SINDIFISC",
    cnpj: "11.099.436/0001-04",
    address: "Rua Rui Barbosa, 215-A - Jd. Olavo Bilac",
    city: "São Bernardo do Campo",
    state: "SP",
    cep: "09725-780",
    phone: "(11) 4122.1959",
    email: "presid@sindifisc.com.br",
    website: "https://www.sindifisc.com.br",
    president: "Claudionor Aparecido Guerra",
    region: "Grande ABC e Litoral Sul",
    category: "Fiscalização, Inspeção e Controle Operacional"
  },
  {
    number: 56,
    name: "Sindicato dos Empregados em Escritórios no Setor Administrativo de Empresas de Transportes Rodoviários de Cargas Secas e Molhadas, Turismo e Fretamento, Urbano e Suburbano de Passageiros, Veículo Zero Km do Grande ABCD e regiões - SEESAETRA",
    cnpj: "02.433.288/0001-13",
    address: "Rua Bernardino de Campos, 346",
    city: "Santo André",
    state: "SP",
    cep: "09015-010",
    phone: "(11) 4438.5668",
    email: "seesaetra@uol.com.br",
    website: "https://www.seesaetra.org.br",
    president: "Joaquim Francisco",
    region: "Grande ABCDMR",
    category: "Escritórios e Administrativo de Transportes"
  },
  {
    number: 57,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários e Anexos ABCDMRP e Rio Grande da Serra - SINTETRA",
    cnpj: "02.433.288/0001-13",
    address: "Rua Santo André, 435 – Vila Assunção",
    city: "Santo André",
    state: "SP",
    cep: "09020-230",
    phone: "(11) 4433.7988",
    email: "diretoria@sintetra.org.br",
    website: "https://www.sintetra.org.br",
    president: "Leandro Mendes da Silva",
    region: "Grande ABCDMRP e Rio Grande da Serra",
    category: "Rodoviários e Anexos"
  },
  {
    number: 58,
    name: "Sindicato dos Trabalhadores Empregados em Transporte Escolar em Veículos de Pequeno, Médio e Grande Porte da Região do ABC - SINTRATESP/ABC",
    cnpj: "11.463.008/0001-00",
    address: "Rua Leila Gonçalves, 96 - Anchieta",
    city: "São Bernardo do Campo",
    state: "SP",
    cep: "09725-051",
    phone: "(11) 2534.6021 e 2381.6075",
    email: "sintratesp.abc1@gmail.com",
    website: "https://www.sintratesp.org.br",
    president: "Aparecido Feliciano Iamarino",
    region: "Grande ABC",
    category: "Transporte Escolar"
  },
  {
    number: 59,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Santos e Região",
    cnpj: "58.194.572/0001-39",
    address: "Avenida Conselheiro Nébias, 262 - Vila Mathias",
    city: "Santos",
    state: "SP",
    cep: "11015-002",
    phone: "(13) 3228.9200",
    email: "secretaria@sindrodsantos.com.br",
    website: "https://www.sindrodsantos.com.br",
    president: "Valdir de Souza Pestana",
    region: "Baixada Santista (Santos, São Vicente, Cubatão, Guarujá, Praia Grande)",
    category: "Transportes Rodoviários e Urbano"
  },
  {
    number: 60,
    name: "Sindicato dos Motoristas Cegonheiros de São Bernardo do Campo - SIMOC",
    cnpj: "05.139.303/0001-03",
    address: "Alameda das Oliveiras, 54 - Vila Jerusalém",
    city: "São Bernardo do Campo",
    state: "SP",
    cep: "09811-380",
    phone: "(11) 4347.0009",
    email: "diretoria@simoc.com.br",
    website: "https://www.simoc.com.br",
    president: "Jacks Douglas Gomes",
    region: "Grande ABC",
    category: "Motoristas Cegonheiros"
  },
  {
    number: 61,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Anexos de São José do Rio Preto e Região",
    cnpj: "60.000.619/0001-28",
    address: "Rua Conselheiro Saraiva nº 101 - Vila Ercilia",
    city: "São José do Rio Preto",
    state: "SP",
    cep: "15046-470",
    phone: "(17) 2137.9700",
    email: "presidencia@sindicatocondutores.com.br",
    website: "https://www.sindicatocondutores.com.br",
    president: "Daniel Candido Rodrigues",
    region: "Noroeste Paulista / Rio Preto",
    category: "Condutores Rodoviários e Anexos"
  },
  {
    number: 62,
    name: "Sindicato dos Empregados em Escritório de Empresas de Transportes Rodoviários no Setor Administrativo de Cargas Secas e Molhadas, Rodoviários Urbanos de Passageiros Intermunicipais, Interestadual, Suburbano, Turismo e Fretamento de São José do Rio Preto, Bauru, Araçatuba e Respectivas Regiões – SEETRO",
    cnpj: "02.679.071/0001-98",
    address: "Rua General Marcondes Salgado, 8-54, Chácara das Flores",
    city: "Bauru",
    state: "SP",
    cep: "17013-113",
    phone: "(17) 3234.6297",
    email: "seetro@uol.com.br",
    website: "https://www.seetro.org.br",
    president: "Lesliane da Silva Veber Miola",
    region: "Rio Preto, Bauru e Araçatuba",
    category: "Escritórios e Setor Administrativo de Transportes"
  },
  {
    number: 63,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de São Manuel, Botucatu, Itatinga, Pardinho e Avaré",
    cnpj: "54.709.191/0001-94",
    address: "Rua Dr. Abílio Gomes, 152 Jd. Tereza Cristina",
    city: "São Manuel",
    state: "SP",
    cep: "18650-000",
    phone: "(14) 3841.4075",
    email: "sindicatotranspsm@outlook.com",
    website: "https://www.fttresp.org.br",
    president: "Geraldo Roberto Naves",
    region: "Botucatu / Avaré",
    category: "Transportes Rodoviários"
  },
  {
    number: 64,
    name: "Sindicato dos Trabalhadores e Instrutores em Auto Escolas, Centro de Formação de Condutores Categorias A e B, Despachantes, Empresas de Transporte Escolar e Anexos da Baixada Santista, Litoral Norte e Sul - SINTRAUTO",
    cnpj: "04.221.840/0001-35",
    address: "Av. Prefeito José Monteiro, 773 – Jd. Independência",
    city: "São Vicente",
    state: "SP",
    cep: "11380-001",
    phone: "(13) 3561.2342 e 3321.3130",
    email: "contato@sintrauto.org.br",
    website: "https://www.sintrauto.org.br",
    president: "José Ernesto Gomes Castilho",
    region: "Baixada Santista, Litoral Norte e Sul",
    category: "Auto Escolas, CFCs, Despachantes e Transporte Escolar"
  },
  {
    number: 65,
    name: "Sindicato dos Condutores de Veículos Rodoviários e Trabalhadores nas Empresas de Transporte Urbano, Passageiros e Fretamento, Intermunicipais, Interestaduais e Cargas de Serrana e região",
    cnpj: "01.201.555/0001-64",
    address: "Rua Lázaro Coutinho de Mattos, 51 - Jd. Bela Vista",
    city: "Serrana",
    state: "SP",
    cep: "14150-000",
    phone: "(16) 3987.6656",
    email: "sintetransc@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Ivan Pereira Lima",
    region: "Ribeirão Preto / Serrana",
    category: "Passageiros, Fretamento e Cargas"
  },
  {
    number: 66,
    name: "Sindicato dos Motoristas, Tratoristas e Operadores de Máquinas Agrícolas das Usinas de Açúcar e Álcool e Destilarias de Serrana",
    cnpj: "04.586.118/0001-02",
    address: "Rua Lázaro Coutinho de Mattos, 51- Jd. Bela Vista",
    city: "Serrana",
    state: "SP",
    cep: "14150-000",
    phone: "(16) 3987.6656",
    email: "sintetransc@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Ivan Pereira Lima",
    region: "Ribeirão Preto / Serrana",
    category: "Usinas, Destilarias e Máquinas Agrícolas"
  },
  {
    number: 67,
    name: "Sindicato dos Motoristas Rodoviários de Fretamento de Transporte de Cargas Secas e Molhadas de Sertãozinho",
    cnpj: "05.506.714/0001-90",
    address: "Rua Sebastião Sampaio nº 535 - Centro",
    city: "Sertãozinho",
    state: "SP",
    cep: "14160-050",
    phone: "(16) 3524.1205",
    email: "simtrosert.stz@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "José Carlos Rullo",
    region: "Ribeirão Preto / Sertãozinho",
    category: "Fretamento e Cargas Secas"
  },
  {
    number: 68,
    name: "Sindicato dos Motoristas, Tratoristas e Operadores de Máquinas Agrícolas das Usinas de Açúcar e Destilaria de Álcool, Fazendas e Sítios de Sertãozinho",
    cnpj: "04.366.116/0001-08",
    address: "Av. José Ferreira dos Reis, 275 Sangri-lá",
    city: "Sertãozinho",
    state: "SP",
    cep: "14160-070",
    phone: "(16) 3945.1401",
    email: "smotorista.stz@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Lazaro Antonio Faria",
    region: "Ribeirão Preto / Sertãozinho",
    category: "Usinas, Destilarias e Máquinas Agrícolas"
  },
  {
    number: 69,
    name: "Sindicato dos Mensageiros Motociclistas, Ciclistas e Moto-Taxistas do Alto Tietê",
    cnpj: "10.384.877/0001-87",
    address: "Rua Caxambu, 142 - Vila Zeferina",
    city: "Itaquaquecetuba",
    state: "SP",
    cep: "08576-010",
    phone: "(11) 4676.4429",
    email: "presidenciacontato@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Walter Chagas de Souza",
    region: "Alto Tietê",
    category: "Motociclistas, Ciclistas e Moto-Taxistas"
  },
  {
    number: 70,
    name: "Sindicato dos Mensageiros Motociclistas, Ciclistas e Moto-Taxistas de Guarulhos e Região",
    cnpj: "09.573.317/0001-91",
    address: "Rua Túlio Brancaleoni, 99 - Centro",
    city: "Guarulhos",
    state: "SP",
    cep: "07110-030",
    phone: "(11) 2087.0790",
    email: "sindimoto-gru@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Eduardo Alves do Couto",
    region: "Grande São Paulo",
    category: "Motociclistas, Ciclistas e Moto-Taxistas"
  },
  {
    number: 71,
    name: "Sindicato dos Mensageiros Motociclistas, Ciclistas e Moto-Taxistas de Osasco e Região",
    cnpj: "10.435.608/0001-00",
    address: "Rua dos Mariano, 454 - Centro",
    city: "Osasco",
    state: "SP",
    cep: "06016-050",
    phone: "(11) 3654.3455",
    email: "diretoriasimosasco@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Marco Antônio da Silva",
    region: "Oeste da Grande SP",
    category: "Motociclistas, Ciclistas e Moto-Taxistas"
  },
  {
    number: 72,
    name: "Sindicato dos Trabalhadores Condutores de Utilitários de Duas Rodas de Ribeirão Preto",
    cnpj: "00.668.155/0001-09",
    address: "Rua Américo Brasiliense, 405 - 9º andar - Edifício Santa Lídia",
    city: "Ribeirão Preto",
    state: "SP",
    cep: "14015-050",
    phone: "(16) 3234.3631 e (16) 98856.0838",
    email: "sindimotorpr@hotmail.com",
    website: "https://www.sindimoto.org.br",
    president: "Danilo Pereira",
    region: "Ribeirão Preto",
    category: "Condutores de Utilitários de Duas Rodas"
  },
  {
    number: 73,
    name: "Sindicato dos Empregados Condutores e Prestadores de Serviços com Veículo de Transporte Rápido Motorizado, Motonetas, Motocicletas e Similares de Santo André, São Bernardo do Campo, São Caetano do Sul, Diadema, Mauá, Ribeirão Pires, Rio Grande da Serra, Suzano e Mogi das Cruzes",
    cnpj: "03.674.446/0001-90",
    address: "Rua Santo André 435",
    city: "Santo André",
    state: "SP",
    cep: "09020-230",
    phone: "(11) 4451.5963",
    email: "sindimotoabc@uol.com.br",
    website: "https://www.fttresp.org.br",
    president: "Carlos Eduardo Tavares",
    region: "Grande ABCD, Suzano e Mogi das Cruzes",
    category: "Motociclistas, Entregadores e Transporte Rápido"
  },
  {
    number: 74,
    name: "Sindicato dos Mensageiros Motociclistas e Ciclistas e Moto-Taxistas e Trabalhadores Nas Empresas de Mensageiros Motociclistas Ciclistas e Moto-Taxistas de Santos e Região",
    cnpj: "10.384.056/0001-40",
    address: "Av. Dr. Bernardino de Campos, 18 - 5º andar – sala 507",
    city: "Santos",
    state: "SP",
    cep: "11075-355",
    phone: "(13) 3221.4754",
    email: "sindimotobaixada@hotmail.com",
    website: "https://www.sindimotobaixada.com.br",
    president: "Alessandro Monteiro de Araújo",
    region: "Baixada Santista",
    category: "Motociclistas e Entregadores"
  },
  {
    number: 75,
    name: "Sindicato dos Mensageiros Motociclistas do Estado de São Paulo - SINDIMOTOSP",
    cnpj: "66.518.978/0001-58",
    address: "Av. Vereador José Diniz, 3.135, 12º andar - Campo Belo",
    city: "São Paulo",
    state: "SP",
    cep: "04603-002",
    phone: "(11) 5094.0075",
    email: "contato@sindimotosp.com.br",
    website: "https://www.sindimotosp.com",
    president: "Gilberto Almeida dos Santos",
    region: "Estado de São Paulo",
    category: "Motociclistas e Entregadores em Geral"
  },
  {
    number: 76,
    name: "Sindicato dos Condutores em Transportes Rodoviário de Cargas Próprias de São Paulo",
    cnpj: "00.769.148/0001-95",
    address: "Rua Conselheiro Crispiniano, 398 - 3º andar",
    city: "São Paulo",
    state: "SP",
    cep: "01037-000",
    phone: "(11) 3334.3560",
    email: "secretaria.geral@cargasproprias.org",
    website: "https://www.cargasproprias.org",
    president: "Almir Macedo Pereira",
    region: "Capital / Estado de SP",
    category: "Transportes de Cargas Próprias"
  },
  {
    number: 77,
    name: "Sindicato dos Empregados Administrativos e Trabalhadores em Escritórios de Empresas de Transportes Rodoviários Terrestres de São Paulo e Itapecerica da Serra - SEATETRISP",
    cnpj: "62.640.131/0001-90",
    address: "Avenida Rangel Pestana 1.292, sala 10 - Brás",
    city: "São Paulo",
    state: "SP",
    cep: "03002-000",
    phone: "(11) 3443.9206 e 3443.9209",
    email: "seatetrisp@gmail.com",
    website: "https://www.fttresp.org.br",
    president: "Luís Gonzaga Barbosa Firmino",
    region: "São Paulo e Itapecerica da Serra",
    category: "Escritórios e Setor Administrativo"
  },
  {
    number: 78,
    name: "Sindicato dos Empregados em Empresas Distribuidoras de Gêneros Alimentícios. Remédios, Jornais e Revistas, de Gás, Materiais para Escritório, Peças e Acessórios para Veículos, Materiais para Construção, Empresas de Sucatas e de Materiais para Reciclagem, Locadoras e Prestadoras de Serviços com Veículos e Empresas Similares do Estado de São Paulo - Seedesp SP",
    cnpj: "02.292.083/0001-65",
    address: "Rua 7 de abril, 264, 6º andar, sala 613",
    city: "São Paulo",
    state: "SP",
    cep: "01044-904",
    phone: "(11) 3237.4949",
    email: "seedesp@seedesp.org.br",
    website: "https://www.seedesp.org.br",
    president: "Walter Jose dos Santos",
    region: "Capital e Estado de SP",
    category: "Distribuidoras, Reciclagem e Locadoras"
  },
  {
    number: 79,
    name: "Sindicato dos Motoristas e Trabalhadores nas Empresas de Taxi no Estado de São Paulo - Simtetaxis SP",
    cnpj: "00.323.500/0001-64",
    address: "Rua Major Freire, 473 - Vila Monte Alegre",
    city: "São Paulo",
    state: "SP",
    cep: "04304-110",
    phone: "(11) 3228.7992 e (11) 93357.5669",
    email: "simtetaxis@gmail.com",
    website: "https://www.simtetaxis.com.br",
    president: "Antônio Raimundo Matias dos Santos",
    region: "Estado de São Paulo",
    category: "Motoristas de Táxi e Frotistas"
  },
  {
    number: 80,
    name: "Sindicato dos Trabalhadores em Depósito de Distribuição de Bebidas de São Paulo, Guarulhos, Osasco, Itapecerica da Serra, Santo André, São Bernardo do Campo, São Caetano do Sul e Diadema - Sindbeb SP",
    cnpj: "00.892.762/0001-40",
    address: "Rua Capitão Cavalcanti, 107 Vila Mariana",
    city: "São Paulo",
    state: "SP",
    cep: "04017-000",
    phone: "(11) 5904.2442 e 5549.5908",
    email: "atendimento@sindbeb.org.br",
    website: "https://www.sindbeb.org.br",
    president: "José Biazon",
    region: "Metropolitana de São Paulo e ABCD",
    category: "Distribuição de Bebidas"
  },
  {
    number: 81,
    name: "Sindicato dos Empregados e Trabalhadores em Empresas Locadoras de Veículos Automotores do Estado de São Paulo Sindelocadesp SP",
    cnpj: "09.632.846/0001-19",
    address: "Rua Tomé Portes, 51 - Vila Dom Pedro II",
    city: "São Paulo",
    state: "SP",
    cep: "02241-010",
    phone: "(11) 3315.0474 e 3129.1724",
    email: "sindelocadesp@uol.com.br",
    website: "https://www.fttresp.org.br",
    president: "Dircelene Batista Ferreira",
    region: "Estado de São Paulo",
    category: "Locadoras de Veículos Automotores"
  },
  {
    number: 82,
    name: "Sindicato dos Empregados em Fiscalização, Inspeção e Controle Operacional nas Empresas de Transporte de Passageiros e Trabalhadores no Sistema de Veículos Leves sobre Canaletas e Pneus no Estado de São Paulo - Sindficot",
    cnpj: "67.142.174/0001-60",
    address: "Rua Barão de Iguape, 339 – Liberdade",
    city: "São Paulo",
    state: "SP",
    cep: "01507-000",
    phone: "(11) 3277.2124 e 3341.2014",
    email: "sindfinancas@hotmail.com",
    website: "https://www.fttresp.org.br",
    president: "Geraldo Abilio de Meireles",
    region: "Estado de São Paulo",
    category: "Fiscalização, Inspeção e Controle Operacional"
  },
  {
    number: 83,
    name: "Sindicato dos Trabalhadores em Cooperativas e Associações do Ramo de Transportes em Ônibus Urbanos Alternativo de São Paulo",
    cnpj: "00.793.879/0001-76",
    address: "Rua Capitão Salomão, 27 - 6º andar, sala 601",
    city: "São Paulo",
    state: "SP",
    cep: "01034-000",
    phone: "(11) 3333.7135",
    email: "sindtrabcoop@terra.com.br",
    website: "https://www.fttresp.org.br",
    president: "Joeliton Lima de Menezes",
    region: "Capital / São Paulo",
    category: "Cooperativas de Ônibus Alternativo"
  },
  {
    number: 84,
    name: "Sindicato dos Trabalhadores em Empresas de Transportes Rodoviários de Cargas Secas e Molhadas, Empresas de Logística no Ramo de Transportes de Cargas de São Paulo e Itapecerica da Serra – Sindicargas SP",
    cnpj: "61.399.689/0001-63",
    address: "Rua Frederico Abranches, 238 - Santa Cecilia",
    city: "São Paulo",
    state: "SP",
    cep: "01225-000",
    phone: "(11) 2858-8366",
    email: "sindicargas@sindicargas.org.br",
    website: "https://www.sindicargas.org.br",
    president: "Natalício Ferreira Alves",
    region: "São Paulo e Itapecerica da Serra",
    category: "Cargas Secas, Molhadas e Logística"
  },
  {
    number: 85,
    name: "Sindicato dos Empregados em Empresas de Transportes de Passageiros por Fretamento e Turismo da Grande São Paulo - Sindifretur SP",
    cnpj: "64.724.370/0001-54",
    address: "Avenida Ipiranga, 324 - 9 Andar - Centro",
    city: "São Paulo",
    state: "SP",
    cep: "01046-922",
    phone: "(11) 3255.0039",
    email: "sindifretur@terra.com.br",
    website: "https://www.sindifretur.com.br",
    president: "Everardo da Costa Baia",
    region: "Região Metropolitana de São Paulo",
    category: "Passageiros por Fretamento e Turismo"
  },
  {
    number: 86,
    name: "Sindicato dos Trabalhadores em Empresas de Transportes, e Remoção de Cargas Especiais, Indivisíveis, Excedentes em Peso e Dimensão, Pesadas e Excepcionais do Estado de São Paulo - Sindipesado SP",
    cnpj: "09.551.018/0001-56",
    address: "Rua Leite de Moraes, 322, Santana",
    city: "São Paulo",
    state: "SP",
    cep: "02034-020",
    phone: "(11) 3326-6607",
    email: "cadastro@sindipesado.org.br",
    website: "https://www.sindipesado.org.br",
    president: "Nivaldo da Silva Almeida",
    region: "Estado de São Paulo",
    category: "Cargas Pesadas, Indivisíveis e Especiais"
  },
  {
    number: 87,
    name: "Sindicato dos Empregados em Escritórios de Empresas de Transportes Rodoviários de Cargas Secas e Molhadas, Cargas Pesadas e Logísticas em Transportes de São Paulo e Itapecerica da Serra - Sindlog",
    cnpj: "05.996.209/0001-70",
    address: "Av. Tiradentes, 1.525 - Luz",
    city: "São Paulo",
    state: "SP",
    cep: "01102-010",
    phone: "(11) 3311.1290",
    email: "presidencia@sindlog.com.br",
    website: "https://www.sindlog.com.br",
    president: "Moacyr Firmino dos Santos",
    region: "São Paulo e Itapecerica da Serra",
    category: "Escritórios de Cargas e Logística"
  },
  {
    number: 88,
    name: "Sindicato dos Motoristas e Trabalhadores em Transporte Rodoviário Urbano de São Paulo (Sindmotoristas)",
    cnpj: "62.656.384/0001-52",
    address: "Rua Pirapitingui, nº 75, Liberdade",
    city: "São Paulo",
    state: "SP",
    cep: "01508-020",
    phone: "(11) 3274-5333",
    email: "presidencia@sindmotoristas.org.br",
    website: "https://www.sindmotoristas.org.br",
    president: "José Valdevan de Jesus Santos (Cristiano Porangaba)",
    region: "Capital / São Paulo",
    category: "Transporte Urbano de Passageiros"
  },
  {
    number: 89,
    name: "Sindicato dos Guincheiros Removedores de Veículos do Estado de São Paulo - Singuesp SP",
    cnpj: "03.368.737/0001-50",
    address: "Rua Herval, 652 – Belenzinho",
    city: "São Paulo",
    state: "SP",
    cep: "03062-000",
    phone: "(11) 2693.5613 e 2693.2548",
    email: "singuesp@singuesp.org",
    website: "https://www.singuesp.org",
    president: "Francisco José Pereira da Silva",
    region: "Estado de São Paulo",
    category: "Guincheiros e Remoção de Veículos"
  },
  {
    number: 90,
    name: "Sindicato dos Trabalhadores nas Empresas de Ônibus Rodoviários, Internacionais, Interestaduais, Intermunicipais e Setor Diferenciado de São Paulo, Itapecerica da Serra, São Lourenço da Serra, Embu Guaçu, Poá, Ferraz de Vasconcelos e Itaquaquecetuba - STERIIISP",
    cnpj: "00.815.065/0001-95",
    address: "Rua Manoel dos Santos Neto, 64 - Carandiru",
    city: "São Paulo",
    state: "SP",
    cep: "02032-010",
    phone: "(11) 2189.5933",
    email: "administracao@sindirodsp.org.br",
    website: "https://www.sindirodsp.org.br",
    president: "José Alves do Couto Filho",
    region: "São Paulo, Itapecerica e Alto Tietê",
    category: "Ônibus Rodoviários, Intermunicipais e Interestaduais"
  },
  {
    number: 91,
    name: "Sindicato dos Trabalhadores e Empregados em Concreteiras e Empresas de Bombeamento e Locação de Bombas no Estado de São Paulo - Sindeconbesp",
    cnpj: "15.112.166/0001-77",
    address: "Rua Voluntários da Pátria, n° 1961, 4° andar – Santana",
    city: "São Paulo",
    state: "SP",
    cep: "02011-400",
    phone: "(11) 2613.7789",
    email: "financeiro@sindeconbesp.org",
    website: "https://www.sindeconbesp.org",
    president: "Jefferson Marcel Canal de Medina",
    region: "Estado de São Paulo",
    category: "Concreteiras e Bombeamento de Concreto"
  },
  {
    number: 92,
    name: "Sindicato dos Trabalhadores no Sistema de Operação, Sinalização, Manutenção, Fiscalização e Planejamento Viário e Urbano do Estado de São Paulo - Sindiviarios",
    cnpj: "66.662.297/0001-69",
    address: "Rua Jesuíno Pascoal, 51- Vila Buarque",
    city: "São Paulo",
    state: "SP",
    cep: "01224-050",
    phone: "(11) 333.8363",
    email: "sindviarios@sindviarios.org.br",
    website: "https://www.sindviarios.org.br",
    president: "Reno Ale",
    region: "Estado de São Paulo",
    category: "Operação, Sinalização, Manutenção e CET"
  },
  {
    number: 93,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários de Sorocaba e Região/SP",
    cnpj: "71.866.529/0001-30",
    address: "Rua Capitão Augusto Franco, 159 - Vila Amélia",
    city: "Sorocaba",
    state: "SP",
    cep: "18.035-615",
    phone: "(15) 3331.7900",
    email: "rodoviario@rodoviariosorocaba.org.br",
    website: "https://www.rodoviariosorocaba.org.br",
    president: "Paulo João Estausia",
    region: "Região Metropolitana de Sorocaba",
    category: "Transportes Rodoviários e Urbano"
  },
  {
    number: 94,
    name: "Sindicato dos Trabalhadores em Transportes Rodoviários do Vale do Paraíba e região",
    cnpj: "48.553.911/0001-72",
    address: "Av. São José, 488 - Jardim Bela Vista",
    city: "São José dos Campos",
    state: "SP",
    cep: "12209-010",
    phone: "(12) 3921.5077",
    email: "organizacao@sindicatodoscondutores.com.br",
    website: "https://www.sindicatodoscondutores.com.br",
    president: "Elias Pereira da Silva",
    region: "Vale do Paraíba, Litoral Norte e Serra da Mantiqueira",
    category: "Transportes Rodoviários e Urbano"
  },
  {
    number: 95,
    name: "Sindicato dos Trabalhadores e Instrutores em Auto Escolas Despachantes e Transportes Escolar Intermunicipal de São Paulo e Região - SINCONTESP",
    cnpj: "59.974.857/0001-55",
    address: "Largo do Paissandu, 51 - 14º andar, sala 1404 - Centro",
    city: "São Paulo",
    state: "SP",
    cep: "01034-900",
    phone: "(11) 3221.5027, 3333.7345 e 3357.6622",
    email: "sincontesp@gmail.com",
    website: "https://www.sincontesp.org.br",
    president: "Jose Petronio Soares Franco",
    region: "Metropolitana de São Paulo",
    category: "Auto Escolas, CFCs, Despachantes e Transporte Escolar"
  },
  {
    number: 96,
    name: "Sindicato dos Trabalhadores em Transporte Escolar do Município de São Paulo e Região - SINTTEASP",
    cnpj: "10.309.777/0001-96",
    address: "Rua Roberto Simonsen, 72",
    city: "São Paulo",
    state: "SP",
    cep: "01017-020",
    phone: "(11) 2289.1137",
    email: "faleconosco@sintteasp.org.br",
    website: "https://www.sintteasp.org",
    president: "Alexandre Gerolamo de Almeida",
    region: "Município de São Paulo e Região",
    category: "Transporte Escolar"
  },
  {
    number: 97,
    name: "Sindicato dos Trabalhadores com Aplicativos de Transporte Terrestre Intermunicipal do Estado de São Paulo - STATTESP",
    cnpj: "30.222.403/0001-46",
    address: "Rua Ribeiro dos Santos, 49",
    city: "São Paulo",
    state: "SP",
    cep: "08010-410",
    phone: "(11) 2297.1392",
    email: "contato@stattesp.com.br",
    website: "https://www.stattesp.com.br",
    president: "Leandro da Cruz Medeiros",
    region: "Estado de São Paulo",
    category: "Trabalhadores por Aplicativo de Transporte"
  }
];

const formattedUnions = rawUnions.map((u) => ({
  id: `u-${u.number}`,
  number: u.number,
  name: `${u.number}. ${u.name}`,
  shortName: u.name.split(' - ')[1] || u.city,
  cnpj: u.cnpj,
  city: u.city,
  state: u.state,
  region: u.region,
  category: u.category,
  phone: u.phone,
  email: u.email,
  address: `${u.address} - ${u.city}/${u.state} - CEP ${u.cep}`,
  cep: u.cep,
  president: u.president,
  website: u.website
}));

// Update database.json
const dbPath = path.join(__dirname, '..', 'server', 'src', 'data', 'database.json');
const dbData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
dbData.unions = formattedUnions;
fs.writeFileSync(dbPath, JSON.stringify(dbData, null, 2), 'utf8');

// Update store.js
const storePath = path.join(__dirname, '..', 'server', 'src', 'data', 'store.js');
let storeContent = fs.readFileSync(storePath, 'utf8');

// Replace unions array in store.js
const unionsRegex = /unions:\s*\[[\s\S]*?\n  \],/;
const newUnionsArray = `unions: ${JSON.stringify(formattedUnions, null, 2)},`;
storeContent = storeContent.replace(unionsRegex, newUnionsArray);
fs.writeFileSync(storePath, storeContent, 'utf8');

console.log(`Sucesso: ${formattedUnions.length} sindicatos oficiais gravados em database.json e store.js!`);
